insert into user (id,email,created_on,last_seen) values (1,'sminogue@yahoo.com',NOW(),NOW());
insert into project (id,name,created_by,`key`,`status`) values (1,'My Library',1,'mylibrary',1);
insert into project (id,name,created_by,`key`,`status`) values (2,'Commons Encryption',1,'commonsencryption',1);
insert into bug (project,reporter,assigned,subject,description,created,modified,status,priority) values (1,1,1,'New Open Assigned Bug Subject','Bug Description',NOW(),NOW(),1,1);
insert into bug (project,reporter,subject,description,created,modified,status,priority) values (1,1,'New Open Unassigned Bug Subject','Bug Description',NOW(),NOW(),1,2);
insert into bug (project,reporter,assigned,subject,description,created,modified,status) values (1,1,1,'New Closed Assigned Bug Subject','Bug Description',NOW(),NOW(),2);
insert into bug (project,reporter,assigned,subject,description,created,modified,status) values (2,1,1,'New Closed Assigned Bug Subject','Bug Description',NOW(),NOW(),2);
insert into bug_label (bug_id,label_id) values (1,1);
insert into bug_label (bug_id,label_id) values (1,2);
insert into bug_label (bug_id,label_id) values (1,3);
insert into bug_label (bug_id,label_id) values (3,2);
insert into bug_label (bug_id,label_id) values (2,1);
insert into comment (contents,created_by,created_on,bug_id) values ('Lorem ipsum Pariatur qui irure in in dolore mollit ullamco laboris non commodo qui deserunt proident in magna laborum.',1,NOW(),1);
insert into comment (contents,created_by,created_on,bug_id) values ('Lorem ipsum Reprehenderit labore deserunt mollit enim aute sunt ut cillum minim esse dolore dolor quis labore dolor id sit labore.',1,DATE_ADD(NOW(),INTERVAL 1 DAY),1);
insert into comment (contents,created_by,created_on,bug_id) values ('Lorem ipsum Eu consectetur ex sed dolor tempor ut reprehenderit proident dolore eu officia nulla in eiusmod.',1,DATE_ADD(NOW(),INTERVAL 2 DAY),1);
insert into comment (contents,created_by,created_on,bug_id) values ('Lorem ipsum Quis tempor qui aute ut irure in elit laboris culpa occaecat labore mollit ea officia qui Ut.',1,DATE_ADD(NOW(),INTERVAL 3 DAY),1);
insert into comment (contents,created_by,created_on,bug_id) values ('Lorem ipsum Pariatur qui irure in in dolore mollit ullamco laboris non commodo qui deserunt proident in magna laborum.',1,NOW(),2);
insert into comment (contents,created_by,created_on,bug_id) values ('Lorem ipsum Reprehenderit labore deserunt mollit enim aute sunt ut cillum minim esse dolore dolor quis labore dolor id sit labore.',1,DATE_ADD(NOW(),INTERVAL 1 DAY),2);
insert into comment (contents,created_by,created_on,bug_id) values ('Lorem ipsum Eu consectetur ex sed dolor tempor ut reprehenderit proident dolore eu officia nulla in eiusmod.',1,DATE_ADD(NOW(),INTERVAL 2 DAY),2);
insert into comment (contents,created_by,created_on,bug_id) values ('Lorem ipsum Quis tempor qui aute ut irure in elit laboris culpa occaecat labore mollit ea officia qui Ut.',1,DATE_ADD(NOW(),INTERVAL 3 DAY),2);